server:
  port: 0
  
  
spring:
  cloud:
    stream:
      bindings:
       fortuneInput:
            destination: fortuneInputDestination
       fortuneResponseOutput:
            destination: fortuneResponseInputDestination