server:
  port: 0
  
  
spring:
  cloud:
    stream:
      bindings:
        JsonFortuneInput:
            destination: fortuneInputDestination
            content-type: application/json 
            
        StringFortuneInput:
            destination: fortuneInputDestination
            content-type: text/plain 

    