server:
  port: 0
   
spring:
  cloud:
    stream:
      bindings:
       fortuneInput:
        destination: fortuneInputDestination
        group: fortuneInputGroup
      rabbit:
       bindings:
        fortuneInput:
         consumer:
          autoBindDlq: false
          republishToDlq : true
          deadLetterQueueName: mydlq 
          deadLetterExchange: mydlq
          deadLetterRoutingKey: rk-mydlq
          
          
          
          